export default [
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p1.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p2.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p3.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p4.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p5.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p6.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p7.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p8.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p9.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p10.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p11.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p12.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p13.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p14.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p15.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p16.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p17.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p18.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p19.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p20.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p21.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p22.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p23.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p24.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p25.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p26.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p27.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p28.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p29.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p30.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p31.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p32.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p33.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p34.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p35.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p36.jpg",
  },
  {
    name: "",
    location: "",
    power: "",
    img: "img/about_projects/p37.jpg",
  },
];
